const express=require('express'); const db=require('../db'); const {authRequired}=require('../auth'); const router=express.Router();
function cart(userId){return db.prepare(`SELECT c.product_id id,p.category,p.name,p.price,p.image,p.badge,p.stock,c.quantity FROM cart_items c JOIN products p ON p.id=c.product_id WHERE c.user_id=? ORDER BY p.id`).all(userId)}
router.get('/cart',authRequired,(req,res)=>res.json({items:cart(req.user.id)}));
router.post('/cart',authRequired,(req,res)=>{const {productId,quantity=1}=req.body||{};const p=db.prepare('SELECT * FROM products WHERE id=?').get(productId);if(!p)return res.status(404).json({error:'Product not found'});if(quantity<1)return res.status(400).json({error:'Quantity must be at least 1'});const existing=db.prepare('SELECT quantity FROM cart_items WHERE user_id=? AND product_id=?').get(req.user.id,productId);const q=Math.min(p.stock,(existing?.quantity||0)+Number(quantity));db.prepare(`INSERT INTO cart_items(user_id,product_id,quantity) VALUES(?,?,?) ON CONFLICT(user_id,product_id) DO UPDATE SET quantity=excluded.quantity,updated_at=CURRENT_TIMESTAMP`).run(req.user.id,productId,q);res.json({items:cart(req.user.id)})});
router.put('/cart/:productId',authRequired,(req,res)=>{const q=Number(req.body?.quantity);if(!Number.isInteger(q)||q<1)return res.status(400).json({error:'Quantity must be a positive integer'});const p=db.prepare('SELECT stock FROM products WHERE id=?').get(req.params.productId);if(!p)return res.status(404).json({error:'Product not found'});db.prepare('UPDATE cart_items SET quantity=?,updated_at=CURRENT_TIMESTAMP WHERE user_id=? AND product_id=?').run(Math.min(q,p.stock),req.user.id,req.params.productId);res.json({items:cart(req.user.id)})});
router.delete('/cart/:productId',authRequired,(req,res)=>{db.prepare('DELETE FROM cart_items WHERE user_id=? AND product_id=?').run(req.user.id,req.params.productId);res.json({items:cart(req.user.id)})});
router.get('/wishlist',authRequired,(req,res)=>res.json({items:db.prepare('SELECT p.* FROM wishlist_items w JOIN products p ON p.id=w.product_id WHERE w.user_id=? ORDER BY p.id').all(req.user.id)}));
router.post('/wishlist/:productId',authRequired,(req,res)=>{const exists=db.prepare('SELECT 1 FROM wishlist_items WHERE user_id=? AND product_id=?').get(req.user.id,req.params.productId);if(exists)db.prepare('DELETE FROM wishlist_items WHERE user_id=? AND product_id=?').run(req.user.id,req.params.productId);else {if(!db.prepare('SELECT 1 FROM products WHERE id=?').get(req.params.productId))return res.status(404).json({error:'Product not found'});db.prepare('INSERT INTO wishlist_items(user_id,product_id) VALUES(?,?)').run(req.user.id,req.params.productId)}res.json({items:db.prepare('SELECT product_id FROM wishlist_items WHERE user_id=?').all(req.user.id).map(x=>x.product_id)})});
router.get('/orders',authRequired,(req,res)=>{const orders=db.prepare('SELECT * FROM orders WHERE user_id=? ORDER BY id DESC').all(req.user.id);for(const o of orders)o.items=db.prepare('SELECT * FROM order_items WHERE order_id=?').all(o.id);res.json({orders})});
router.post('/orders',authRequired,(req,res)=>{
 const {customerName,email,phone,address,city,pincode}=req.body||{}; if(!customerName||!email||!phone||!address||!city||!pincode)return res.status(400).json({error:'All delivery fields are required'});
 const items=cart(req.user.id); if(!items.length)return res.status(400).json({error:'Your cart is empty'});
 for(const i of items) if(i.quantity>i.stock)return res.status(400).json({error:`Only ${i.stock} of ${i.name} are available`});
 const total=items.reduce((s,i)=>s+i.price*i.quantity,0);
 const tx=db.transaction(()=>{const o=db.prepare('INSERT INTO orders(user_id,customer_name,email,phone,address,city,pincode,total) VALUES(?,?,?,?,?,?,?,?)').run(req.user.id,customerName,email,phone,address,city,pincode,total);const oid=o.lastInsertRowid;const ins=db.prepare('INSERT INTO order_items(order_id,product_id,product_name,price,quantity) VALUES(?,?,?,?,?)');const stock=db.prepare('UPDATE products SET stock=stock-? WHERE id=?');for(const i of items){ins.run(oid,i.id,i.name,i.price,i.quantity);stock.run(i.quantity,i.id)}db.prepare('DELETE FROM cart_items WHERE user_id=?').run(req.user.id);return oid});
 const oid=tx();res.status(201).json({message:'Order placed successfully',order:db.prepare('SELECT * FROM orders WHERE id=?').get(oid)});
});
router.post('/orders/:id/cancel',authRequired,(req,res)=>{const o=db.prepare('SELECT * FROM orders WHERE id=? AND user_id=?').get(req.params.id,req.user.id);if(!o)return res.status(404).json({error:'Order not found'});if(o.status!=='Placed'&&o.status!=='Processing')return res.status(400).json({error:'Order can no longer be cancelled'});if(Date.now()-new Date(o.created_at).getTime()>2*864e5)return res.status(400).json({error:'Cancellation window of 2 days has expired'});const tx=db.transaction(()=>{const items=db.prepare('SELECT * FROM order_items WHERE order_id=?').all(o.id);const stock=db.prepare('UPDATE products SET stock=stock+? WHERE id=?');for(const it of items)stock.run(it.quantity,it.product_id);db.prepare("UPDATE orders SET status='Cancelled' WHERE id=?").run(o.id)});tx();const updated=db.prepare('SELECT * FROM orders WHERE id=?').get(o.id);return res.json({message:'Order cancelled successfully',order:updated})});
module.exports=router;
